excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://kongkow.github.io
title: Blog Ratakan Pejwan
tagline: A log of everyday life
description: Kumpulan Tulisan yang bermanfaat untuk kesehatan blog anda
paginate: 3